<#
.SYNOPSIS
Runs an end-to-end troubleshooting session for an Azure Arc managed server.

.DESCRIPTION
Collects system state, Arc diagnostics, optional drift and AMA diagnostics,
performs troubleshooting analysis, optionally runs remediation, and finishes with
deployment-health validation. The cmdlet also creates a transcript and JSON report
under the selected output path.

.PARAMETER ServerName
Target server to analyze.

.PARAMETER WorkspaceId
Optional Log Analytics workspace identifier used for AMA diagnostics.

.PARAMETER AutoRemediate
Attempts remediation actions generated by troubleshooting analysis.

.PARAMETER DetailedAnalysis
Requests deeper diagnostics collection where supported.

.PARAMETER OutputPath
Directory used for transcript and JSON report output.

.PARAMETER DriftBaselinePath
Optional drift baseline file used during configuration drift validation.

.OUTPUTS
PSCustomObject

.EXAMPLE
Start-ArcTroubleshooter -ServerName 'SERVER01' -WorkspaceId '<workspace-id>' -DetailedAnalysis -OutputPath '.\Logs'
#>
function Start-ArcTroubleshooter {
    [CmdletBinding(SupportsShouldProcess)]
    param (
        [Parameter(Mandatory)]
        [string]$ServerName,
        [Parameter()]
        [string]$WorkspaceId,
        [Parameter()]
        [switch]$AutoRemediate,
        [Parameter()]
        [switch]$DetailedAnalysis,
        [Parameter()]
        [string]$OutputPath = "./Logs",
        [Parameter()]
        [string]$DriftBaselinePath
    )

    begin {
        $troubleshootingSession = @{
            SessionId = [guid]::NewGuid().ToString()
            ServerName = $ServerName
            StartTime = Get-Date
            Status = "Starting"
            Components = @()
            Remediation = @()
        }

        # Start logging
        $logPath = Join-Path $OutputPath "ArcTroubleshooting_$(Get-Date -Format 'yyyyMMdd_HHmmss').log"
        Start-Transcript -Path $logPath
        Write-Verbose "Starting troubleshooting session $($troubleshootingSession.SessionId)"
    }

    process {
        try {
            # 1. Initial System State
            Write-Progress -Activity "Arc Troubleshooter" -Status "Collecting System State" -PercentComplete 10
            $systemState = Get-SystemState -ServerName $ServerName
            $troubleshootingSession.Components += @{
                Phase = "SystemState"
                Data = $systemState
                Timestamp = Get-Date
            }

            # 2. Arc Agent Diagnostics
            Write-Progress -Activity "Arc Troubleshooter" -Status "Arc Agent Diagnostics" -PercentComplete 30
            $arcDiagnostics = Invoke-ArcDiagnosticCollection -ServerName $ServerName -DetailedAnalysis:$DetailedAnalysis -WorkspaceId $WorkspaceId
            $troubleshootingSession.Components += @{
                Phase = "ArcDiagnostics"
                Data = $arcDiagnostics
                Timestamp = Get-Date
            }

            # 2b. Configuration Drift (optional baseline)
            Write-Progress -Activity "Arc Troubleshooter" -Status "Configuration Drift" -PercentComplete 40
            $driftParams = @{ ServerName = $ServerName }
            if (-not [string]::IsNullOrWhiteSpace($DriftBaselinePath)) { $driftParams.BaselinePath = $DriftBaselinePath }
            $driftReport = Test-ConfigurationDrift @driftParams
            $troubleshootingSession.Components += @{
                Phase = "ConfigurationDrift"
                Data = $driftReport
                Timestamp = Get-Date
            }

            # 3. AMA Diagnostics (if workspace provided)
            if ($WorkspaceId) {
                Write-Progress -Activity "Arc Troubleshooter" -Status "AMA Diagnostics" -PercentComplete 50
                $amaDiagnostics = Start-AMADiagnostics -ServerName $ServerName -WorkspaceId $WorkspaceId
                $troubleshootingSession.Components += @{
                    Phase = "AMADiagnostics"
                    Data = $amaDiagnostics
                    Timestamp = Get-Date
                }
            }

            # 4. Analysis
            Write-Progress -Activity "Arc Troubleshooter" -Status "Analyzing Results" -PercentComplete 70
            $analysis = Invoke-ArcTroubleshootingAnalysis -Data $troubleshootingSession.Components
            $troubleshootingSession.Analysis = $analysis

            # 5. Remediation (if enabled)
            if ($AutoRemediate) {
                Write-Progress -Activity "Arc Troubleshooter" -Status "Performing Remediation" -PercentComplete 85
                $troubleshootingSession.Remediation += Invoke-ArcRemediationWorkflow -Analysis $analysis -ServerName $ServerName
            }

            # 6. Final Validation
            Write-Progress -Activity "Arc Troubleshooter" -Status "Final Validation" -PercentComplete 95
            $finalValidation = Test-DeploymentHealth -ServerName $ServerName -ValidateAMA:($null -ne $WorkspaceId)
            $troubleshootingSession.FinalState = $finalValidation

            $troubleshootingSession.Status = "Completed"
        }
        catch {
            $troubleshootingSession.Status = "Failed"
            $troubleshootingSession.Error = @{
                Message = $_.Exception.Message
                Details = $_.Exception.StackTrace
                Timestamp = Get-Date
            }
            Write-Log -Message "Troubleshooting session failed: $($_.Exception.Message)" -Level Error -Component 'Start-ArcTroubleshooter'
            Write-Verbose "Start-ArcTroubleshooter caught error: $($_.Exception.Message)"
        }
    }

    end {
        # Generate detailed report
        $report = Get-TroubleshootingReportObject -Session $troubleshootingSession
        $reportPath = Join-Path $OutputPath "TroubleshootingReport_$(Get-Date -Format 'yyyyMMdd_HHmmss').json"
        $report | ConvertTo-Json -Depth 10 | Out-File $reportPath

        Stop-Transcript
        return [PSCustomObject]$troubleshootingSession
    }
}

function Invoke-ArcDiagnosticCollection {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory)]
        [string]$ServerName,
        [Parameter()]
        [switch]$DetailedAnalysis,
        [Parameter()]
        [string]$WorkspaceId
    )

    if (-not (Get-Command Start-ArcDiagnostics -ErrorAction SilentlyContinue)) {
        $diagnosticsScriptPath = Join-Path $PSScriptRoot 'Start-ArcDiagnostics.ps1'
        if (Test-Path $diagnosticsScriptPath -PathType Leaf) {
            . $diagnosticsScriptPath
        }
    }

    $diagnosticParams = @{
        ServerName = $ServerName
        DetailedScan = $DetailedAnalysis
    }

    if (-not [string]::IsNullOrWhiteSpace($WorkspaceId)) {
        $diagnosticParams.WorkspaceId = $WorkspaceId
    }

    return Start-ArcDiagnostics @diagnosticParams
}

function Invoke-ArcTroubleshootingAnalysis {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory)]
        [object[]]$Data
    )

    if (Get-Command Invoke-TroubleshootingAnalysis -ErrorAction SilentlyContinue) {
        return Invoke-TroubleshootingAnalysis -Data $Data
    }

    if (Get-Command Invoke-ArcAnalysis -ErrorAction SilentlyContinue) {
        $diagnosticData = [ordered]@{}
        foreach ($component in $Data) {
            if ($component -and $component.Phase) {
                $diagnosticData[$component.Phase] = $component.Data
            }
        }

        return Invoke-ArcAnalysis -DiagnosticData $diagnosticData
    }

    throw 'No troubleshooting analysis command is available.'
}

function Invoke-ArcRemediationWorkflow {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory)]
        [object]$Analysis,
        [Parameter(Mandatory)]
        [string]$ServerName
    )

    if (Get-Command Start-IssueRemediation -ErrorAction SilentlyContinue) {
        $remediations = @()
        foreach ($issue in @($Analysis.Issues)) {
            $remediations += Start-IssueRemediation -Issue $issue -ServerName $ServerName
        }

        return $remediations
    }

    if (Get-Command Start-ArcRemediation -ErrorAction SilentlyContinue) {
        return @(Start-ArcRemediation -AnalysisResults $Analysis -ServerName $ServerName)
    }

    return @()
}

function Get-TroubleshootingReportObject {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory)]
        [hashtable]$Session
    )

    if (Get-Command New-TroubleshootingReport -ErrorAction SilentlyContinue) {
        return New-TroubleshootingReport -Session $Session
    }

    return [PSCustomObject]$Session
}